### ISSUE TITLE
Warlock casting Upheaval until end

### ISSUE THREAD

**Issue by ThirVondukr** [forest0xia/dota2bot-OpenHyperAI#21] opened 2024-09-09 19:02 UTC
Warlock disregards his safety and just continues to cast upheaval regardless of the situation

**Comment by forest0xia** [comment] 2024-09-10 20:02
I had tried to stop Warlock doing this in the past: https://github.com/forest0xia/dota2bot-OpenHyperAI/blame/main/bots/BotLib/hero_warlock.lua#L227
It wasn't effective and I forgot about it after the try. 
This is definitely something we should fix. Thanks for calling it out

**Comment by forest0xia** [comment] 2024-09-10 20:04
Think the issue is inside the ConsiderStop that can get fixed by just changing the conditions

**Comment by forest0xia** [comment] 2024-10-21 07:35
hey @ThirVondukr, how are you doing. Asking if you have any plan on this?

**Closed** 2024-11-08 21:17 UTC
